version: '3.8'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: debtmanager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    environment:
      DATASOURCE_URL: jdbc:postgresql://postgres:5432/debtmanager
      DATASOURCE_USERNAME: postgres
      DATASOURCE_PASSWORD: postgres

volumes:
  postgres_data:
