version: '3.8'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: debtmanager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - debt-network

  app:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      SERVER_PORT: 8081
      ACTIVE_PROFILE: homolog
      DATASOURCE_URL: jdbc:postgresql://postgres:5432/debtmanager
      DATASOURCE_USERNAME: postgres
      DATASOURCE_PASSWORD: postgres
      SHOW_SQL: "true"
    networks:
      - debt-network

volumes:
  postgres_data:

networks:
  debt-network:
    driver: bridge
