-- Adiciona a tabela installment
CREATE TABLE IF NOT EXISTS installment
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    debt_id      BIGINT                                  NOT NULL,
    amount       DECIMAL                                  NOT NULL,
    due_date     DATE                                     NOT NULL,
    paid         BOOLEAN                                  NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_installment PRIMARY KEY (id)
);

-- Adiciona a constraint de chave estrangeira na tabela installment
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_installment_on_debt') THEN
        ALTER TABLE installment
            ADD CONSTRAINT FK_INSTALLMENT_ON_DEBT FOREIGN KEY (debt_id) REFERENCES debt (id);
    END IF;
END $$;

-- Ajustes nas tabelas existentes, se necessário
-- Adiciona uma nova coluna last_payment_date à tabela debt para gerenciar a data do último pagamento (opcional)
ALTER TABLE debt
    ADD COLUMN IF NOT EXISTS last_payment_date DATE;

-- Atualiza a constraint de chave estrangeira na tabela payment (se necessário)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_payment_on_debt') THEN
        ALTER TABLE payment
            ADD CONSTRAINT FK_PAYMENT_ON_DEBT FOREIGN KEY (debt_id) REFERENCES debt (id);
    END IF;
END $$;
