CREATE TABLE IF NOT EXISTS debt
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date_create            TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    date_update            TIMESTAMP WITHOUT TIME ZONE,
    total_amount           DECIMAL,
    principal_amount       DECIMAL,
    creditor_name          VARCHAR(255),
    due_date               date,
    number_of_installments INTEGER,
    interest_rate          DECIMAL,
    status                 VARCHAR(255),
    CONSTRAINT pk_debt PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS payment
(
    id                           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date_create           TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    date_update TIMESTAMP WITHOUT TIME ZONE,
    debt_id                      BIGINT                                  NOT NULL,
    amount                       DECIMAL,
    payment_date                 date,
    CONSTRAINT pk_payment PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS payment
    ADD CONSTRAINT FK_PAYMENT_ON_DEBT FOREIGN KEY (debt_id) REFERENCES debt (id);
